FROM ruby:3.0

RUN curl https://deb.nodesource.com/setup_14.x | bash

	RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -qq && apt-get install -y build-essential nodejs yarn mariadb-client && rm -rf /var/lib/apt/lists/*

ENV APP_PATH /live-chat-rails

RUN mkdir $APP_PATH

WORKDIR $APP_PATH

COPY /live-chat-rails/Gemfile $APP_PATH/Gemfile
COPY /live-chat-rails/Gemfile.lock $APP_PATH/Gemfile.lock
RUN bundle install

COPY . $APP_PATH

COPY /live-chat-rails/entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]